### ISSUE TITLE
Improve CI efficiency

### ISSUE THREAD

**Issue by forgottosave** [AP-Sensing/ostree-tui#20]
### Description

The CI introduced in https://github.com/AP-Sensing/ostree-tui/pull/19 can be drastically improved in efficiency, by creating a custom docker/container image based on fedora:latest where all dependencies required in most builds are already installed.

### Tasks
- [ ] Create custom container including all dependencies
- [ ] Rebuild image automatically every once in a while so it stays up to date
- [ ] As mentioned by @COM8, maybe it can be hosted inside the GitHub container registry, this needs further investigation (https://github.blog/news-insights/product-news/introducing-github-container-registry/)
- [ ] Another side thing that would also improve "efficiency": Maybe properly define, what CI should run on which event (currently a lot of jobs run twice on a push to a PR)
